#!/bin/bash

if [ -z "$1" ]; then
  db="greenarrow-studio_development"
else
  db="$1"
fi

echo "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='$db'" | psql
dropdb $db &&
createdb $db &&
ssh root@staging.drh.net pg_dump --no-owner --no-privileges --no-acl -U greenarrow greenarrow \> alex-ga.dmp &&
scp -C root@staging.drh.net:alex-ga.dmp /tmp/ga.dmp &&
perl -p -i -e "s/ offset integer/ offset1 integer/g" /tmp/ga.dmp &&
perl -p -i -e "s/\\+ offset\\)/+ offset1)/g" /tmp/ga.dmp &&
perl -p -i -e "s/STRICT offset FROM/STRICT offset1 FROM/g" /tmp/ga.dmp &&
psql $db < /tmp/ga.dmp &&
rm -f /tmp/ga.dmp
